// <auto-generated />
using System;
using MediatrixPruebaTecnica.Gateways.RepositoryEFCore.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediatrixPruebaTecnica.Gateways.RepositoryEFCore.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20251130083620_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MediatrixPruebaTecnica.Entities.Bases.Empleado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroSeguroSocial")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoEmpleado")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("Id");

                    b.HasIndex("Departamento");

                    b.HasIndex("NumeroSeguroSocial")
                        .IsUnique();

                    b.ToTable("Empleados", (string)null);

                    b.HasDiscriminator<string>("TipoEmpleado").HasValue("Empleado");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MediatrixPruebaTecnica.Entities.POCOs.RegistroPago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Deducciones")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("EmpleadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoBruto")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MontoNeto")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PeriodoFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodoInicio")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId", "FechaPago");

                    b.ToTable("RegistrosPagos", (string)null);
                });

            modelBuilder.Entity("MediatrixPruebaTecnica.Entities.POCOs.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("MediatrixPruebaTecnica.Entities.POCOs.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("MediatrixPruebaTecnica.Entities.POCOs.EmpleadoAsalariado", b =>
                {
                    b.HasBaseType("MediatrixPruebaTecnica.Entities.Bases.Empleado");

                    b.Property<decimal>("SalarioSemanal")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("Asalariado");
                });

            modelBuilder.Entity("MediatrixPruebaTecnica.Entities.POCOs.EmpleadoAsalariadoPorComision", b =>
                {
                    b.HasBaseType("MediatrixPruebaTecnica.Entities.Bases.Empleado");

                    b.Property<decimal>("SalarioBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TarifaComision")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VentasBrutas")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("AsalariadoPorComision");
                });

            modelBuilder.Entity("MediatrixPruebaTecnica.Entities.POCOs.EmpleadoPorComision", b =>
                {
                    b.HasBaseType("MediatrixPruebaTecnica.Entities.Bases.Empleado");

                    b.Property<decimal>("TarifaComision")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VentasBrutas")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("Empleados", t =>
                        {
                            t.Property("TarifaComision")
                                .HasColumnName("EmpleadoPorComision_TarifaComision");

                            t.Property("VentasBrutas")
                                .HasColumnName("EmpleadoPorComision_VentasBrutas");
                        });

                    b.HasDiscriminator().HasValue("PorComision");
                });

            modelBuilder.Entity("MediatrixPruebaTecnica.Entities.POCOs.EmpleadoPorHoras", b =>
                {
                    b.HasBaseType("MediatrixPruebaTecnica.Entities.Bases.Empleado");

                    b.Property<decimal>("HorasTrabajadas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SueldoPorHora")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("PorHoras");
                });

            modelBuilder.Entity("MediatrixPruebaTecnica.Entities.POCOs.RegistroPago", b =>
                {
                    b.HasOne("MediatrixPruebaTecnica.Entities.Bases.Empleado", "Empleado")
                        .WithMany("RegistrosPagos")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("MediatrixPruebaTecnica.Entities.POCOs.Usuario", b =>
                {
                    b.HasOne("MediatrixPruebaTecnica.Entities.POCOs.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("MediatrixPruebaTecnica.Entities.Bases.Empleado", b =>
                {
                    b.Navigation("RegistrosPagos");
                });

            modelBuilder.Entity("MediatrixPruebaTecnica.Entities.POCOs.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
