<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="EmpleadoControllers\" />
    <Folder Include="RegistroPagoControllers\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MediatrixPruebaTecnica.Presenters\MediatrixPruebaTecnica.Presenters.csproj" />
    <ProjectReference Include="..\MediatrixPruebaTexnica.UseCasesPorts\MediatrixPruebaTexnica.UseCasesPorts.csproj" />
  </ItemGroup>

</Project>
